article/urls.py
from . import views
from django.contrib import admin
from django.urls import path

app_name= "article"
urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addcomment,name="comment"),

   
    
]

djangoapp/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
   
    path('about/',views.about,name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name ="user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.signin,name="login"),
    path('logout/',views.signout,name="logout"),
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title =models.TextField()
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_image=models.FileField(blank=True,null =True,verbose_name="Article add")
    def __str__(self):
        return self.title
    class Meta:
        ordering =['-created_date']  
class Comment(models.Model):
    article =models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="article",related_name="comments")
    comment_author = models.TextField( verbose_name="name")
    comment_content = models.TextField (verbose_name="comment")
    comment_date =models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']
    


    

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):    
    class Meta:
        model=Article
        fields=["title","content","article_image"]

user/forms.py
from django import forms
class RegisterForm(forms.Form):
    username =forms.CharField(max_length=50,label="username")
    password =forms.CharField(max_length=20,label="password",widget=forms.PasswordInput)
    confirm=forms.CharField(max_length=20,label="confirm",widget=forms.PasswordInput)
    def clean(self):
        username=self.cleaned_data.get("username") 
        password = self.cleaned_data.get("password")
        confirm=self.cleaned_data.get("confirm")
        if password and confirm and password != confirm:
            raise forms.ValidationError("passwords did not match")
        values={
            "username":username,
            "password":password
        }
        return values
class LoginForm(forms.Form):
    username =forms.CharField(label="username")
    password=forms.CharField(label="password",widget =forms.PasswordInput)

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,"index.html")
def about(request):
    return render(request,"about.html")
@login_required(login_url ="user:login")
def dashboard(request):
    articles = Article.objects.filter(author =request.user)
    context ={
        "articles":articles
    }

    return render(request,"dashboard.html",context)
@login_required(login_url ="user:login")
def addArticle(request):
    form =ArticleForm(request.POST or None,request.FILES or None)
    context={
        "form":form
    }
    if form.is_valid():
        article=form.save(commit=False)
        article.author =request.user
        article.save()
        messages.success(request,"article was created")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",context)

def detail(request,id):
    #article =Article.objects.filter(id=id).first()
    article=get_object_or_404(Article,id=id)
    comments =article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})


@login_required(login_url ="user:login")
def updateArticle(request,id):
    article=get_object_or_404(Article,id=id)
    form =ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article=form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"the article was updated.")
        return redirect("index")
    
    return render(request,"update.html",{"form":form})
@login_required(login_url ="user:login")
def deleteArticle(request,id):
    article=get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"the article was deleted")
    return redirect("article:dashboard")
    
def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request,"articles.html",{"articles":articles})
    articles =Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def addcomment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author =request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment =Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect (reverse("article:detail",kwargs={"id":id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages

# Create your views here.
def register(request):
    form =RegisterForm(request.POST or None)
    if form.is_valid():
        username =form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        newUser =User(username=username)
        newUser.set_password(password)
        newUser.save()
        login(request,newUser)
        messages.info(request,"your registration was completed")
        return redirect("index")
    context ={
        "form":form
    }    
    return render(request,"register.html",context)     
        
    

def signin(request):
    form =LoginForm(request.POST or None)
    context={
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password =form.cleaned_data.get("password")
        user=authenticate(username=username,password=password)
        if user is None:
            messages.info(request,"username or password is invalid")
            return render(request,"login.html",context)
        messages.success(request,"you logined")
        login(request,user)
        return redirect("index")

    messages.info(request,"username or password is invalid")
    return render(request,"login.html",context)



def signout(request):
    logout(request)
    messages.success(request,"you signed out")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}
{% block body %}
<div class="jumbotron text">
<h3>What is Python?</h3>
<hr>
<p>In technical terms, Python is an object-oriented, high-level programming language with integrated dynamic semantics primarily for web and app development. It is extremely attractive in the field of Rapid Application Development because it offers dynamic typing and dynamic binding options. 
 
Python is relatively simple, so it's easy to learn since it requires a unique syntax that focuses on readability. Developers can read and translate Python code much easier than other languages. In turn, this reduces the cost of program maintenance and development because it allows teams to work collaboratively without significant language and experience barriers.
 
Additionally, Python supports the use of modules and packages, which means that programs can be designed in a modular style and code can be reused across a variety of projects. Once you've developed a module or package you need, it can be scaled for use in other projects, and it's easy to import or export these modules.
 
One of the most promising benefits of Python is that both the standard library and the interpreter are available free of charge, in both binary and source form. There is no exclusivity either, as Python and all the necessary tools are available on all major platforms. Therefore, it is an enticing option for developers who don't want to worry about paying high development costs.
 
If this description of Python over your head, don't worry. You'll understand it soon enough. What you need to take away from this section is that Python is a programming language used to develop software on the web and in app form, including mobile. It's relatively easy to learn, and the necessary tools are available to all free of charge.
 
That makes Python accessible to almost anyone. If you have the time to learn, you can create some amazing things with the language.
 </p>
 </div>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% block body %}


{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
      
        <hr>
        <form method = "post" enctype="multipart/form-data">
        <h3>update article form<h3>
        <hr>
            {% csrf_token %}
           {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">add article</button>
        </form>
    </div>
  </div>

   


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}

    <div class= "row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>articles</h3>
                <hr>
                </div>
        </div>

</div>
{% if articles %}
{% for article in  articles %}
<div class ="row">
<div class="col-md-10 offset-md-3">



 
 
    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4"><a href = "{% url 'article:detail' article.id %}">{{article.title}}</a></h3>

      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} by published
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:10}}
      </p>
 <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">continue read</a>
      <hr>
</div>
</div>
</div>     

{% endfor %}
{% else %}
<div class ="row">
    
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class= "alert alert-danger"> there are not any articles.   </div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}

<h3>dashboard</h3>
<hr>

<p> wellcome ,
<small>{{request.user.username}}</small>  </p>
<hr>
<a class = "btn btn-danger" href="/articles/addarticle">add article</a>
<hr>
{% if articles %}
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">title</th>
      <th scope="col">author</th>
      <th scope="col">date</th>
        <th scope="col">update</th>
          <th scope="col">delete</th>
          <tbody>
          {% for article in articles  %}
          <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href ="/articles/article/{{article.id}}">{{article.title}} </a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="/articles/update/{{article.id}}" class ="btn btn-danger">update</a></td>
      <td><a href ="/articles/delete/{{article.id}}" class="btn btn-danger">delete</a></td>
       </tr>

          
          {% endfor %}
       
    
    
  </tbody>
    </tr>
  </thead>
 
</table>

{% else %}
<div class ="aler alert-danger">your article is not exist yet.</div>
{% endif %}














{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} by published
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>

      <hr>

      <h4>comments</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
      
      {% else %}
      <div class ="alert alert-danger">
       this article is not commented
      </div>
      {% endif %}

      <div class="card my-4">
          <h5 class="card-header">add comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="name entered">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">add</button>
            </form>
          </div>
        </div>
        </div>
        
      </div>


{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index'  %}">BLOG <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href= "{% url 'about'  %}">ABOUT</a>
      </li>     
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:articles'  %}">ARTİCLES</a>
      </li>    
     
    </ul>
    <ul class="navbar-nav ml-auto">
    {% if request.user.is_authenticated  %}
    <li class="nav-item active">     
        <a class="nav-link disabled" href="#">{{request.user.username}}  </a>
      </li>
   <li class="nav-item active">
        <a class="nav-link disabled" href="{% url 'article:dashboard'  %}">DASHBOARD </a>
      </li>
    <li class="nav-item active">
     
        <a class="nav-link disabled" href="{% url  'user:logout'  %}"> LOG OUT  </a>
      </li>
    {% else %}
<li class="nav-item active">
        <a class="nav-link disabled" href="{% url 'user:login'  %}">SIGN IN </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link disabled" href="{% url 'user:register'  %}">SIGN UP </a>
      </li>
    {% endif %}
    

 
    
      
    </ul>

    
  </div>
</nav>

templates/index.html
{% extends "layout.html" %}
{% block body %}
<br>

<div class ="jumbotron text-center">
    <h1 class="display-3">Software Application</h1>
    <p class="lead">Python -Django framework</p>
    <hr class="my-2">
    <hr>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">articles</a>
    </p>
</div>


{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <title>Document</title>
</head>
<body>
{% include "includes/navbar.html" %}
<br>
<div class="row">
<div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
<form class="form-inline my-2 my-lg-0">
{% csrf_token %}
      <input class="form-control mr-sm-2" name="keyword" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
    </div>
    </div>
<div style ="margin-top: 25px; margin-bottom:50px;" class="container">
       {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}

{% block body %}

{% endblock body %}




<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<h3>Login<h3>
<hr>
<div class="row">
    <div class="col-md-6 offset-md-3">
      
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">submit</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
<h3>sign up</h3>
<hr><hr>
<form method ="post">
{% csrf_token %}
{{form|crispy}}
<button type="submit" class="btn btn-danger">submit</button>
</form>


{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
      
        <hr>
        <form method = "post" enctype="multipart/form-data">
        <h3>article form<h3>
        <hr>
            {% csrf_token %}
           {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">update article</button>
        </form>
    </div>
  </div>

   




{% endblock body %}